// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: Proto/SquidGame.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespuestaUnirse_JUEGO int32

const (
	RespuestaUnirse_Luces       RespuestaUnirse_JUEGO = 0
	RespuestaUnirse_TirarCuerda RespuestaUnirse_JUEGO = 1
	RespuestaUnirse_TodoNada    RespuestaUnirse_JUEGO = 2
)

// Enum value maps for RespuestaUnirse_JUEGO.
var (
	RespuestaUnirse_JUEGO_name = map[int32]string{
		0: "Luces",
		1: "TirarCuerda",
		2: "TodoNada",
	}
	RespuestaUnirse_JUEGO_value = map[string]int32{
		"Luces":       0,
		"TirarCuerda": 1,
		"TodoNada":    2,
	}
)

func (x RespuestaUnirse_JUEGO) Enum() *RespuestaUnirse_JUEGO {
	p := new(RespuestaUnirse_JUEGO)
	*p = x
	return p
}

func (x RespuestaUnirse_JUEGO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespuestaUnirse_JUEGO) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_SquidGame_proto_enumTypes[0].Descriptor()
}

func (RespuestaUnirse_JUEGO) Type() protoreflect.EnumType {
	return &file_Proto_SquidGame_proto_enumTypes[0]
}

func (x RespuestaUnirse_JUEGO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespuestaUnirse_JUEGO.Descriptor instead.
func (RespuestaUnirse_JUEGO) EnumDescriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{1, 0}
}

type RespuestaEnviarJugada_ESTADO int32

const (
	RespuestaEnviarJugada_ESTADO_MUERTO  RespuestaEnviarJugada_ESTADO = 0
	RespuestaEnviarJugada_ESTADO_VIVO    RespuestaEnviarJugada_ESTADO = 1
	RespuestaEnviarJugada_ESTADO_GANADOR RespuestaEnviarJugada_ESTADO = 2
)

// Enum value maps for RespuestaEnviarJugada_ESTADO.
var (
	RespuestaEnviarJugada_ESTADO_name = map[int32]string{
		0: "ESTADO_MUERTO",
		1: "ESTADO_VIVO",
		2: "ESTADO_GANADOR",
	}
	RespuestaEnviarJugada_ESTADO_value = map[string]int32{
		"ESTADO_MUERTO":  0,
		"ESTADO_VIVO":    1,
		"ESTADO_GANADOR": 2,
	}
)

func (x RespuestaEnviarJugada_ESTADO) Enum() *RespuestaEnviarJugada_ESTADO {
	p := new(RespuestaEnviarJugada_ESTADO)
	*p = x
	return p
}

func (x RespuestaEnviarJugada_ESTADO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespuestaEnviarJugada_ESTADO) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_SquidGame_proto_enumTypes[1].Descriptor()
}

func (RespuestaEnviarJugada_ESTADO) Type() protoreflect.EnumType {
	return &file_Proto_SquidGame_proto_enumTypes[1]
}

func (x RespuestaEnviarJugada_ESTADO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespuestaEnviarJugada_ESTADO.Descriptor instead.
func (RespuestaEnviarJugada_ESTADO) EnumDescriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{5, 0}
}

type SolicitudUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solictud string `protobuf:"bytes,1,opt,name=solictud,proto3" json:"solictud,omitempty"`
}

func (x *SolicitudUnirse) Reset() {
	*x = SolicitudUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudUnirse) ProtoMessage() {}

func (x *SolicitudUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudUnirse.ProtoReflect.Descriptor instead.
func (*SolicitudUnirse) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudUnirse) GetSolictud() string {
	if x != nil {
		return x.Solictud
	}
	return ""
}

type RespuestaUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId            `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	NumJuego   RespuestaUnirse_JUEGO `protobuf:"varint,2,opt,name=numJuego,proto3,enum=Proto.RespuestaUnirse_JUEGO" json:"numJuego,omitempty"`
}

func (x *RespuestaUnirse) Reset() {
	*x = RespuestaUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaUnirse) ProtoMessage() {}

func (x *RespuestaUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaUnirse.ProtoReflect.Descriptor instead.
func (*RespuestaUnirse) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaUnirse) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *RespuestaUnirse) GetNumJuego() RespuestaUnirse_JUEGO {
	if x != nil {
		return x.NumJuego
	}
	return RespuestaUnirse_Luces
}

type SolicitudVerMonto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SolicitudVerMonto) Reset() {
	*x = SolicitudVerMonto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudVerMonto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudVerMonto) ProtoMessage() {}

func (x *SolicitudVerMonto) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudVerMonto.ProtoReflect.Descriptor instead.
func (*SolicitudVerMonto) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{2}
}

type RespuestaVerMonto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto float32 `protobuf:"fixed32,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *RespuestaVerMonto) Reset() {
	*x = RespuestaVerMonto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaVerMonto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaVerMonto) ProtoMessage() {}

func (x *RespuestaVerMonto) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaVerMonto.ProtoReflect.Descriptor instead.
func (*RespuestaVerMonto) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaVerMonto) GetMonto() float32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type SolicitudEnviarJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadaInfo *JugadaRondaJugador `protobuf:"bytes,1,opt,name=jugadaInfo,proto3" json:"jugadaInfo,omitempty"`
}

func (x *SolicitudEnviarJugada) Reset() {
	*x = SolicitudEnviarJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudEnviarJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEnviarJugada) ProtoMessage() {}

func (x *SolicitudEnviarJugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEnviarJugada.ProtoReflect.Descriptor instead.
func (*SolicitudEnviarJugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{4}
}

func (x *SolicitudEnviarJugada) GetJugadaInfo() *JugadaRondaJugador {
	if x != nil {
		return x.JugadaInfo
	}
	return nil
}

type RespuestaEnviarJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado RespuestaEnviarJugada_ESTADO `protobuf:"varint,1,opt,name=estado,proto3,enum=Proto.RespuestaEnviarJugada_ESTADO" json:"estado,omitempty"`
}

func (x *RespuestaEnviarJugada) Reset() {
	*x = RespuestaEnviarJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEnviarJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEnviarJugada) ProtoMessage() {}

func (x *RespuestaEnviarJugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEnviarJugada.ProtoReflect.Descriptor instead.
func (*RespuestaEnviarJugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaEnviarJugada) GetEstado() RespuestaEnviarJugada_ESTADO {
	if x != nil {
		return x.Estado
	}
	return RespuestaEnviarJugada_ESTADO_MUERTO
}

type SolicitudRegistrarJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugador *JugadasJugador `protobuf:"bytes,1,opt,name=jugadasJugador,proto3" json:"jugadasJugador,omitempty"`
}

func (x *SolicitudRegistrarJugadas) Reset() {
	*x = SolicitudRegistrarJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudRegistrarJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRegistrarJugadas) ProtoMessage() {}

func (x *SolicitudRegistrarJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRegistrarJugadas.ProtoReflect.Descriptor instead.
func (*SolicitudRegistrarJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{6}
}

func (x *SolicitudRegistrarJugadas) GetJugadasJugador() *JugadasJugador {
	if x != nil {
		return x.JugadasJugador
	}
	return nil
}

type RespuestaRegistrarJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
}

func (x *RespuestaRegistrarJugadas) Reset() {
	*x = RespuestaRegistrarJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaRegistrarJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRegistrarJugadas) ProtoMessage() {}

func (x *RespuestaRegistrarJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRegistrarJugadas.ProtoReflect.Descriptor instead.
func (*RespuestaRegistrarJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{7}
}

func (x *RespuestaRegistrarJugadas) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

type SolicitudDevolverRegistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
}

func (x *SolicitudDevolverRegistro) Reset() {
	*x = SolicitudDevolverRegistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudDevolverRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudDevolverRegistro) ProtoMessage() {}

func (x *SolicitudDevolverRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudDevolverRegistro.ProtoReflect.Descriptor instead.
func (*SolicitudDevolverRegistro) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{8}
}

func (x *SolicitudDevolverRegistro) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

type RespuestaDevolverRegistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugador *JugadasJugador `protobuf:"bytes,1,opt,name=jugadasJugador,proto3" json:"jugadasJugador,omitempty"`
}

func (x *RespuestaDevolverRegistro) Reset() {
	*x = RespuestaDevolverRegistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaDevolverRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaDevolverRegistro) ProtoMessage() {}

func (x *RespuestaDevolverRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaDevolverRegistro.ProtoReflect.Descriptor instead.
func (*RespuestaDevolverRegistro) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{9}
}

func (x *RespuestaDevolverRegistro) GetJugadasJugador() *JugadasJugador {
	if x != nil {
		return x.JugadasJugador
	}
	return nil
}

type JugadorId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *JugadorId) Reset() {
	*x = JugadorId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadorId) ProtoMessage() {}

func (x *JugadorId) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadorId.ProtoReflect.Descriptor instead.
func (*JugadorId) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{10}
}

func (x *JugadorId) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type RondaId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *RondaId) Reset() {
	*x = RondaId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RondaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RondaId) ProtoMessage() {}

func (x *RondaId) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RondaId.ProtoReflect.Descriptor instead.
func (*RondaId) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{11}
}

func (x *RondaId) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{12}
}

func (x *Jugada) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type JugadaRondaJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	NumRonda   *RondaId   `protobuf:"bytes,2,opt,name=numRonda,proto3" json:"numRonda,omitempty"`
	Jugada     *Jugada    `protobuf:"bytes,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *JugadaRondaJugador) Reset() {
	*x = JugadaRondaJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadaRondaJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadaRondaJugador) ProtoMessage() {}

func (x *JugadaRondaJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadaRondaJugador.ProtoReflect.Descriptor instead.
func (*JugadaRondaJugador) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{13}
}

func (x *JugadaRondaJugador) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *JugadaRondaJugador) GetNumRonda() *RondaId {
	if x != nil {
		return x.NumRonda
	}
	return nil
}

func (x *JugadaRondaJugador) GetJugada() *Jugada {
	if x != nil {
		return x.Jugada
	}
	return nil
}

type JugadasRonda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRonda *RondaId  `protobuf:"bytes,1,opt,name=numRonda,proto3" json:"numRonda,omitempty"`
	Jugadas  []*Jugada `protobuf:"bytes,2,rep,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *JugadasRonda) Reset() {
	*x = JugadasRonda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasRonda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasRonda) ProtoMessage() {}

func (x *JugadasRonda) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasRonda.ProtoReflect.Descriptor instead.
func (*JugadasRonda) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{14}
}

func (x *JugadasRonda) GetNumRonda() *RondaId {
	if x != nil {
		return x.NumRonda
	}
	return nil
}

func (x *JugadasRonda) GetJugadas() []*Jugada {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

type JugadasJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador   *JugadorId      `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	JugadasRonda []*JugadasRonda `protobuf:"bytes,2,rep,name=jugadasRonda,proto3" json:"jugadasRonda,omitempty"`
}

func (x *JugadasJugador) Reset() {
	*x = JugadasJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasJugador) ProtoMessage() {}

func (x *JugadasJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasJugador.ProtoReflect.Descriptor instead.
func (*JugadasJugador) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{15}
}

func (x *JugadasJugador) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *JugadasJugador) GetJugadasRonda() []*JugadasRonda {
	if x != nil {
		return x.JugadasRonda
	}
	return nil
}

type JugadasRondaJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador   *JugadorId    `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	JugadasRonda *JugadasRonda `protobuf:"bytes,2,opt,name=jugadasRonda,proto3" json:"jugadasRonda,omitempty"`
}

func (x *JugadasRondaJugador) Reset() {
	*x = JugadasRondaJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasRondaJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasRondaJugador) ProtoMessage() {}

func (x *JugadasRondaJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasRondaJugador.ProtoReflect.Descriptor instead.
func (*JugadasRondaJugador) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{16}
}

func (x *JugadasRondaJugador) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *JugadasRondaJugador) GetJugadasRonda() *JugadasRonda {
	if x != nil {
		return x.JugadasRonda
	}
	return nil
}

type Jugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugadores []*JugadasJugador `protobuf:"bytes,1,rep,name=jugadasJugadores,proto3" json:"jugadasJugadores,omitempty"`
}

func (x *Jugadas) Reset() {
	*x = Jugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugadas) ProtoMessage() {}

func (x *Jugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugadas.ProtoReflect.Descriptor instead.
func (*Jugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{17}
}

func (x *Jugadas) GetJugadasJugadores() []*JugadasJugador {
	if x != nil {
		return x.JugadasJugadores
	}
	return nil
}

var File_Proto_SquidGame_proto protoreflect.FileDescriptor

var file_Proto_SquidGame_proto_rawDesc = []byte{
	0x0a, 0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x71, 0x75, 0x69, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d,
	0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x55, 0x6e, 0x69, 0x72, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x74, 0x75, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x74, 0x75, 0x64, 0x22, 0xb0, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x2e, 0x4a, 0x55,
	0x45, 0x47, 0x4f, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x31, 0x0a,
	0x05, 0x4a, 0x55, 0x45, 0x47, 0x4f, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x75, 0x63, 0x65, 0x73, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x69, 0x72, 0x61, 0x72, 0x43, 0x75, 0x65, 0x72, 0x64, 0x61,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x4e, 0x61, 0x64, 0x61, 0x10, 0x02,
	0x22, 0x13, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x56, 0x65, 0x72,
	0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f,
	0x22, 0x52, 0x0a, 0x15, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x45, 0x6e, 0x76,
	0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52, 0x6f, 0x6e, 0x64,
	0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0a, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x3b,
	0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x2e, 0x45, 0x53, 0x54,
	0x41, 0x44, 0x4f, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x40, 0x0a, 0x06, 0x45,
	0x53, 0x54, 0x41, 0x44, 0x4f, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x53, 0x54, 0x41, 0x44, 0x4f, 0x5f,
	0x4d, 0x55, 0x45, 0x52, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x53, 0x54, 0x41,
	0x44, 0x4f, 0x5f, 0x56, 0x49, 0x56, 0x4f, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x53, 0x54,
	0x41, 0x44, 0x4f, 0x5f, 0x47, 0x41, 0x4e, 0x41, 0x44, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x5a, 0x0a,
	0x19, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x19, 0x52, 0x65, 0x73,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75,
	0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x19, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x5a, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x6f, 0x12, 0x3d, 0x0a, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x52, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x22, 0x1d, 0x0a, 0x09, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x1b, 0x0a, 0x07, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22,
	0x1a, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x99, 0x01, 0x0a, 0x12,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x12, 0x25, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52,
	0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x63, 0x0a, 0x0c, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x2a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f,
	0x6e, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f,
	0x6e, 0x64, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x22, 0x7b, 0x0a, 0x0e,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x30,
	0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x12, 0x37, 0x0a, 0x0c, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x52, 0x0c, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x0c, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f,
	0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x52, 0x0c,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x22, 0x4c, 0x0a, 0x07,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x41, 0x0a, 0x10, 0x6a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x10, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x32, 0xcd, 0x01, 0x0a, 0x05, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x12, 0x16,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x1a, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x08, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x18, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x56, 0x65, 0x72, 0x4d,
	0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x4a,
	0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x1c,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x1c, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x6e,
	0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x32, 0x46, 0x0a, 0x04, 0x50, 0x6f,
	0x7a, 0x6f, 0x12, 0x3e, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x18,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x74, 0x6f, 0x32, 0xb9, 0x01, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x56, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x12, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x73, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x6f, 0x6c,
	0x76, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x20, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x65, 0x76, 0x6f,
	0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a, 0x20, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x65,
	0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x32, 0xb9,
	0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x56, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12,
	0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75,
	0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x42, 0x28, 0x5a, 0x26, 0x43, 0x3a,
	0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x4c, 0x61, 0x62, 0x32, 0x49, 0x4e, 0x46, 0x33, 0x34, 0x33, 0x2f, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_SquidGame_proto_rawDescOnce sync.Once
	file_Proto_SquidGame_proto_rawDescData = file_Proto_SquidGame_proto_rawDesc
)

func file_Proto_SquidGame_proto_rawDescGZIP() []byte {
	file_Proto_SquidGame_proto_rawDescOnce.Do(func() {
		file_Proto_SquidGame_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_SquidGame_proto_rawDescData)
	})
	return file_Proto_SquidGame_proto_rawDescData
}

var file_Proto_SquidGame_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Proto_SquidGame_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_Proto_SquidGame_proto_goTypes = []interface{}{
	(RespuestaUnirse_JUEGO)(0),        // 0: Proto.RespuestaUnirse.JUEGO
	(RespuestaEnviarJugada_ESTADO)(0), // 1: Proto.RespuestaEnviarJugada.ESTADO
	(*SolicitudUnirse)(nil),           // 2: Proto.SolicitudUnirse
	(*RespuestaUnirse)(nil),           // 3: Proto.RespuestaUnirse
	(*SolicitudVerMonto)(nil),         // 4: Proto.SolicitudVerMonto
	(*RespuestaVerMonto)(nil),         // 5: Proto.RespuestaVerMonto
	(*SolicitudEnviarJugada)(nil),     // 6: Proto.SolicitudEnviarJugada
	(*RespuestaEnviarJugada)(nil),     // 7: Proto.RespuestaEnviarJugada
	(*SolicitudRegistrarJugadas)(nil), // 8: Proto.SolicitudRegistrarJugadas
	(*RespuestaRegistrarJugadas)(nil), // 9: Proto.RespuestaRegistrarJugadas
	(*SolicitudDevolverRegistro)(nil), // 10: Proto.SolicitudDevolverRegistro
	(*RespuestaDevolverRegistro)(nil), // 11: Proto.RespuestaDevolverRegistro
	(*JugadorId)(nil),                 // 12: Proto.JugadorId
	(*RondaId)(nil),                   // 13: Proto.RondaId
	(*Jugada)(nil),                    // 14: Proto.Jugada
	(*JugadaRondaJugador)(nil),        // 15: Proto.JugadaRondaJugador
	(*JugadasRonda)(nil),              // 16: Proto.JugadasRonda
	(*JugadasJugador)(nil),            // 17: Proto.JugadasJugador
	(*JugadasRondaJugador)(nil),       // 18: Proto.JugadasRondaJugador
	(*Jugadas)(nil),                   // 19: Proto.Jugadas
}
var file_Proto_SquidGame_proto_depIdxs = []int32{
	12, // 0: Proto.RespuestaUnirse.numJugador:type_name -> Proto.JugadorId
	0,  // 1: Proto.RespuestaUnirse.numJuego:type_name -> Proto.RespuestaUnirse.JUEGO
	15, // 2: Proto.SolicitudEnviarJugada.jugadaInfo:type_name -> Proto.JugadaRondaJugador
	1,  // 3: Proto.RespuestaEnviarJugada.estado:type_name -> Proto.RespuestaEnviarJugada.ESTADO
	17, // 4: Proto.SolicitudRegistrarJugadas.jugadasJugador:type_name -> Proto.JugadasJugador
	12, // 5: Proto.RespuestaRegistrarJugadas.numJugador:type_name -> Proto.JugadorId
	12, // 6: Proto.SolicitudDevolverRegistro.numJugador:type_name -> Proto.JugadorId
	17, // 7: Proto.RespuestaDevolverRegistro.jugadasJugador:type_name -> Proto.JugadasJugador
	12, // 8: Proto.JugadaRondaJugador.numJugador:type_name -> Proto.JugadorId
	13, // 9: Proto.JugadaRondaJugador.numRonda:type_name -> Proto.RondaId
	14, // 10: Proto.JugadaRondaJugador.jugada:type_name -> Proto.Jugada
	13, // 11: Proto.JugadasRonda.numRonda:type_name -> Proto.RondaId
	14, // 12: Proto.JugadasRonda.jugadas:type_name -> Proto.Jugada
	12, // 13: Proto.JugadasJugador.numJugador:type_name -> Proto.JugadorId
	16, // 14: Proto.JugadasJugador.jugadasRonda:type_name -> Proto.JugadasRonda
	12, // 15: Proto.JugadasRondaJugador.numJugador:type_name -> Proto.JugadorId
	16, // 16: Proto.JugadasRondaJugador.jugadasRonda:type_name -> Proto.JugadasRonda
	17, // 17: Proto.Jugadas.jugadasJugadores:type_name -> Proto.JugadasJugador
	2,  // 18: Proto.Lider.Unirse:input_type -> Proto.SolicitudUnirse
	4,  // 19: Proto.Lider.VerMonto:input_type -> Proto.SolicitudVerMonto
	6,  // 20: Proto.Lider.EnviarJugada:input_type -> Proto.SolicitudEnviarJugada
	4,  // 21: Proto.Pozo.VerMonto:input_type -> Proto.SolicitudVerMonto
	8,  // 22: Proto.NameNode.RegistrarJugadas:input_type -> Proto.SolicitudRegistrarJugadas
	10, // 23: Proto.NameNode.DevolverJugadas:input_type -> Proto.SolicitudDevolverRegistro
	8,  // 24: Proto.DataNode.RegistrarJugadas:input_type -> Proto.SolicitudRegistrarJugadas
	10, // 25: Proto.DataNode.DevolverJugadas:input_type -> Proto.SolicitudDevolverRegistro
	3,  // 26: Proto.Lider.Unirse:output_type -> Proto.RespuestaUnirse
	5,  // 27: Proto.Lider.VerMonto:output_type -> Proto.RespuestaVerMonto
	7,  // 28: Proto.Lider.EnviarJugada:output_type -> Proto.RespuestaEnviarJugada
	5,  // 29: Proto.Pozo.VerMonto:output_type -> Proto.RespuestaVerMonto
	9,  // 30: Proto.NameNode.RegistrarJugadas:output_type -> Proto.RespuestaRegistrarJugadas
	11, // 31: Proto.NameNode.DevolverJugadas:output_type -> Proto.RespuestaDevolverRegistro
	9,  // 32: Proto.DataNode.RegistrarJugadas:output_type -> Proto.RespuestaRegistrarJugadas
	11, // 33: Proto.DataNode.DevolverJugadas:output_type -> Proto.RespuestaDevolverRegistro
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_Proto_SquidGame_proto_init() }
func file_Proto_SquidGame_proto_init() {
	if File_Proto_SquidGame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_SquidGame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudVerMonto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaVerMonto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudEnviarJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaEnviarJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudRegistrarJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaRegistrarJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudDevolverRegistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaDevolverRegistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadorId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RondaId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadaRondaJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasRonda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasRondaJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_SquidGame_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_Proto_SquidGame_proto_goTypes,
		DependencyIndexes: file_Proto_SquidGame_proto_depIdxs,
		EnumInfos:         file_Proto_SquidGame_proto_enumTypes,
		MessageInfos:      file_Proto_SquidGame_proto_msgTypes,
	}.Build()
	File_Proto_SquidGame_proto = out.File
	file_Proto_SquidGame_proto_rawDesc = nil
	file_Proto_SquidGame_proto_goTypes = nil
	file_Proto_SquidGame_proto_depIdxs = nil
}
