// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: Proto/SquidGame.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JUEGO int32

const (
	JUEGO_None        JUEGO = 0
	JUEGO_Luces       JUEGO = 1
	JUEGO_TirarCuerda JUEGO = 2
	JUEGO_TodoNada    JUEGO = 3
)

// Enum value maps for JUEGO.
var (
	JUEGO_name = map[int32]string{
		0: "None",
		1: "Luces",
		2: "TirarCuerda",
		3: "TodoNada",
	}
	JUEGO_value = map[string]int32{
		"None":        0,
		"Luces":       1,
		"TirarCuerda": 2,
		"TodoNada":    3,
	}
)

func (x JUEGO) Enum() *JUEGO {
	p := new(JUEGO)
	*p = x
	return p
}

func (x JUEGO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JUEGO) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_SquidGame_proto_enumTypes[0].Descriptor()
}

func (JUEGO) Type() protoreflect.EnumType {
	return &file_Proto_SquidGame_proto_enumTypes[0]
}

func (x JUEGO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JUEGO.Descriptor instead.
func (JUEGO) EnumDescriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{0}
}

type ESTADO int32

const (
	ESTADO_Muerto  ESTADO = 0
	ESTADO_Vivo    ESTADO = 1
	ESTADO_Ganador ESTADO = 2
)

// Enum value maps for ESTADO.
var (
	ESTADO_name = map[int32]string{
		0: "Muerto",
		1: "Vivo",
		2: "Ganador",
	}
	ESTADO_value = map[string]int32{
		"Muerto":  0,
		"Vivo":    1,
		"Ganador": 2,
	}
)

func (x ESTADO) Enum() *ESTADO {
	p := new(ESTADO)
	*p = x
	return p
}

func (x ESTADO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESTADO) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_SquidGame_proto_enumTypes[1].Descriptor()
}

func (ESTADO) Type() protoreflect.EnumType {
	return &file_Proto_SquidGame_proto_enumTypes[1]
}

func (x ESTADO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESTADO.Descriptor instead.
func (ESTADO) EnumDescriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{1}
}

type RespuestaUnirse_TIPO int32

const (
	RespuestaUnirse_Esperar  RespuestaUnirse_TIPO = 0
	RespuestaUnirse_Comenzar RespuestaUnirse_TIPO = 1
)

// Enum value maps for RespuestaUnirse_TIPO.
var (
	RespuestaUnirse_TIPO_name = map[int32]string{
		0: "Esperar",
		1: "Comenzar",
	}
	RespuestaUnirse_TIPO_value = map[string]int32{
		"Esperar":  0,
		"Comenzar": 1,
	}
)

func (x RespuestaUnirse_TIPO) Enum() *RespuestaUnirse_TIPO {
	p := new(RespuestaUnirse_TIPO)
	*p = x
	return p
}

func (x RespuestaUnirse_TIPO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespuestaUnirse_TIPO) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_SquidGame_proto_enumTypes[2].Descriptor()
}

func (RespuestaUnirse_TIPO) Type() protoreflect.EnumType {
	return &file_Proto_SquidGame_proto_enumTypes[2]
}

func (x RespuestaUnirse_TIPO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespuestaUnirse_TIPO.Descriptor instead.
func (RespuestaUnirse_TIPO) EnumDescriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{1, 0}
}

type SolicitudUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solictud string `protobuf:"bytes,1,opt,name=solictud,proto3" json:"solictud,omitempty"`
}

func (x *SolicitudUnirse) Reset() {
	*x = SolicitudUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudUnirse) ProtoMessage() {}

func (x *SolicitudUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudUnirse.ProtoReflect.Descriptor instead.
func (*SolicitudUnirse) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudUnirse) GetSolictud() string {
	if x != nil {
		return x.Solictud
	}
	return ""
}

type RespuestaUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgTipo    RespuestaUnirse_TIPO `protobuf:"varint,1,opt,name=msgTipo,proto3,enum=Proto.RespuestaUnirse_TIPO" json:"msgTipo,omitempty"`
	NumJugador *JugadorId           `protobuf:"bytes,2,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	NumJuego   JUEGO                `protobuf:"varint,3,opt,name=numJuego,proto3,enum=Proto.JUEGO" json:"numJuego,omitempty"`
	NumRonda   *RondaId             `protobuf:"bytes,4,opt,name=numRonda,proto3" json:"numRonda,omitempty"`
}

func (x *RespuestaUnirse) Reset() {
	*x = RespuestaUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaUnirse) ProtoMessage() {}

func (x *RespuestaUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaUnirse.ProtoReflect.Descriptor instead.
func (*RespuestaUnirse) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaUnirse) GetMsgTipo() RespuestaUnirse_TIPO {
	if x != nil {
		return x.MsgTipo
	}
	return RespuestaUnirse_Esperar
}

func (x *RespuestaUnirse) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *RespuestaUnirse) GetNumJuego() JUEGO {
	if x != nil {
		return x.NumJuego
	}
	return JUEGO_None
}

func (x *RespuestaUnirse) GetNumRonda() *RondaId {
	if x != nil {
		return x.NumRonda
	}
	return nil
}

type SolicitudVerMonto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SolicitudVerMonto) Reset() {
	*x = SolicitudVerMonto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudVerMonto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudVerMonto) ProtoMessage() {}

func (x *SolicitudVerMonto) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudVerMonto.ProtoReflect.Descriptor instead.
func (*SolicitudVerMonto) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{2}
}

type RespuestaVerMonto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto float32 `protobuf:"fixed32,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *RespuestaVerMonto) Reset() {
	*x = RespuestaVerMonto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaVerMonto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaVerMonto) ProtoMessage() {}

func (x *RespuestaVerMonto) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaVerMonto.ProtoReflect.Descriptor instead.
func (*RespuestaVerMonto) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaVerMonto) GetMonto() float32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type SolicitudEnviarJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadaInfo *PaqueteJugada `protobuf:"bytes,1,opt,name=jugadaInfo,proto3" json:"jugadaInfo,omitempty"`
}

func (x *SolicitudEnviarJugada) Reset() {
	*x = SolicitudEnviarJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudEnviarJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEnviarJugada) ProtoMessage() {}

func (x *SolicitudEnviarJugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEnviarJugada.ProtoReflect.Descriptor instead.
func (*SolicitudEnviarJugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{4}
}

func (x *SolicitudEnviarJugada) GetJugadaInfo() *PaqueteJugada {
	if x != nil {
		return x.JugadaInfo
	}
	return nil
}

type RespuestaEnviarJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado ESTADO `protobuf:"varint,1,opt,name=estado,proto3,enum=Proto.ESTADO" json:"estado,omitempty"`
}

func (x *RespuestaEnviarJugada) Reset() {
	*x = RespuestaEnviarJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEnviarJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEnviarJugada) ProtoMessage() {}

func (x *RespuestaEnviarJugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEnviarJugada.ProtoReflect.Descriptor instead.
func (*RespuestaEnviarJugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaEnviarJugada) GetEstado() ESTADO {
	if x != nil {
		return x.Estado
	}
	return ESTADO_Muerto
}

type SolicitudRegistrarJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugador *JugadasJugador `protobuf:"bytes,1,opt,name=jugadasJugador,proto3" json:"jugadasJugador,omitempty"`
}

func (x *SolicitudRegistrarJugadas) Reset() {
	*x = SolicitudRegistrarJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudRegistrarJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRegistrarJugadas) ProtoMessage() {}

func (x *SolicitudRegistrarJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRegistrarJugadas.ProtoReflect.Descriptor instead.
func (*SolicitudRegistrarJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{6}
}

func (x *SolicitudRegistrarJugadas) GetJugadasJugador() *JugadasJugador {
	if x != nil {
		return x.JugadasJugador
	}
	return nil
}

type RespuestaRegistrarJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
}

func (x *RespuestaRegistrarJugadas) Reset() {
	*x = RespuestaRegistrarJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaRegistrarJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRegistrarJugadas) ProtoMessage() {}

func (x *RespuestaRegistrarJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRegistrarJugadas.ProtoReflect.Descriptor instead.
func (*RespuestaRegistrarJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{7}
}

func (x *RespuestaRegistrarJugadas) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

type SolicitudDevolverJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
}

func (x *SolicitudDevolverJugadas) Reset() {
	*x = SolicitudDevolverJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudDevolverJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudDevolverJugadas) ProtoMessage() {}

func (x *SolicitudDevolverJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudDevolverJugadas.ProtoReflect.Descriptor instead.
func (*SolicitudDevolverJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{8}
}

func (x *SolicitudDevolverJugadas) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

type RespuestaDevolverJugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugador *JugadasJugador `protobuf:"bytes,1,opt,name=jugadasJugador,proto3" json:"jugadasJugador,omitempty"`
}

func (x *RespuestaDevolverJugadas) Reset() {
	*x = RespuestaDevolverJugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaDevolverJugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaDevolverJugadas) ProtoMessage() {}

func (x *RespuestaDevolverJugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaDevolverJugadas.ProtoReflect.Descriptor instead.
func (*RespuestaDevolverJugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{9}
}

func (x *RespuestaDevolverJugadas) GetJugadasJugador() *JugadasJugador {
	if x != nil {
		return x.JugadasJugador
	}
	return nil
}

type JugadorId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *JugadorId) Reset() {
	*x = JugadorId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadorId) ProtoMessage() {}

func (x *JugadorId) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadorId.ProtoReflect.Descriptor instead.
func (*JugadorId) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{10}
}

func (x *JugadorId) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type RondaId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *RondaId) Reset() {
	*x = RondaId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RondaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RondaId) ProtoMessage() {}

func (x *RondaId) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RondaId.ProtoReflect.Descriptor instead.
func (*RondaId) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{11}
}

func (x *RondaId) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int32 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{12}
}

func (x *Jugada) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type PaqueteJugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador *JugadorId `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	NumJuego   JUEGO      `protobuf:"varint,2,opt,name=numJuego,proto3,enum=Proto.JUEGO" json:"numJuego,omitempty"`
	NumRonda   *RondaId   `protobuf:"bytes,3,opt,name=numRonda,proto3" json:"numRonda,omitempty"`
	Jugada     *Jugada    `protobuf:"bytes,4,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *PaqueteJugada) Reset() {
	*x = PaqueteJugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteJugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteJugada) ProtoMessage() {}

func (x *PaqueteJugada) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteJugada.ProtoReflect.Descriptor instead.
func (*PaqueteJugada) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{13}
}

func (x *PaqueteJugada) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *PaqueteJugada) GetNumJuego() JUEGO {
	if x != nil {
		return x.NumJuego
	}
	return JUEGO_None
}

func (x *PaqueteJugada) GetNumRonda() *RondaId {
	if x != nil {
		return x.NumRonda
	}
	return nil
}

func (x *PaqueteJugada) GetJugada() *Jugada {
	if x != nil {
		return x.Jugada
	}
	return nil
}

type JugadasRonda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRonda *RondaId  `protobuf:"bytes,1,opt,name=numRonda,proto3" json:"numRonda,omitempty"`
	Jugadas  []*Jugada `protobuf:"bytes,2,rep,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *JugadasRonda) Reset() {
	*x = JugadasRonda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasRonda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasRonda) ProtoMessage() {}

func (x *JugadasRonda) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasRonda.ProtoReflect.Descriptor instead.
func (*JugadasRonda) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{14}
}

func (x *JugadasRonda) GetNumRonda() *RondaId {
	if x != nil {
		return x.NumRonda
	}
	return nil
}

func (x *JugadasRonda) GetJugadas() []*Jugada {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

type JugadasJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador   *JugadorId      `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	JugadasRonda []*JugadasRonda `protobuf:"bytes,2,rep,name=jugadasRonda,proto3" json:"jugadasRonda,omitempty"`
}

func (x *JugadasJugador) Reset() {
	*x = JugadasJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasJugador) ProtoMessage() {}

func (x *JugadasJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasJugador.ProtoReflect.Descriptor instead.
func (*JugadasJugador) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{15}
}

func (x *JugadasJugador) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *JugadasJugador) GetJugadasRonda() []*JugadasRonda {
	if x != nil {
		return x.JugadasRonda
	}
	return nil
}

type JugadasRondaJugador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumJugador   *JugadorId    `protobuf:"bytes,1,opt,name=numJugador,proto3" json:"numJugador,omitempty"`
	JugadasRonda *JugadasRonda `protobuf:"bytes,2,opt,name=jugadasRonda,proto3" json:"jugadasRonda,omitempty"`
}

func (x *JugadasRondaJugador) Reset() {
	*x = JugadasRondaJugador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasRondaJugador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasRondaJugador) ProtoMessage() {}

func (x *JugadasRondaJugador) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasRondaJugador.ProtoReflect.Descriptor instead.
func (*JugadasRondaJugador) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{16}
}

func (x *JugadasRondaJugador) GetNumJugador() *JugadorId {
	if x != nil {
		return x.NumJugador
	}
	return nil
}

func (x *JugadasRondaJugador) GetJugadasRonda() *JugadasRonda {
	if x != nil {
		return x.JugadasRonda
	}
	return nil
}

type Jugadas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JugadasJugadores []*JugadasJugador `protobuf:"bytes,1,rep,name=jugadasJugadores,proto3" json:"jugadasJugadores,omitempty"`
}

func (x *Jugadas) Reset() {
	*x = Jugadas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_SquidGame_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugadas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugadas) ProtoMessage() {}

func (x *Jugadas) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_SquidGame_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugadas.ProtoReflect.Descriptor instead.
func (*Jugadas) Descriptor() ([]byte, []int) {
	return file_Proto_SquidGame_proto_rawDescGZIP(), []int{17}
}

func (x *Jugadas) GetJugadasJugadores() []*JugadasJugador {
	if x != nil {
		return x.JugadasJugadores
	}
	return nil
}

var File_Proto_SquidGame_proto protoreflect.FileDescriptor

var file_Proto_SquidGame_proto_rawDesc = []byte{
	0x0a, 0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x71, 0x75, 0x69, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d,
	0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x55, 0x6e, 0x69, 0x72, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x74, 0x75, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x74, 0x75, 0x64, 0x22, 0xf3, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x2e, 0x54, 0x49, 0x50, 0x4f, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x69, 0x70, 0x6f, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a,
	0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x6e, 0x75,
	0x6d, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x55, 0x45, 0x47, 0x4f, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x4a,
	0x75, 0x65, 0x67, 0x6f, 0x12, 0x2a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x22, 0x21, 0x0a, 0x04, 0x54, 0x49, 0x50, 0x4f, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x73, 0x70, 0x65,
	0x72, 0x61, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x65, 0x6e, 0x7a, 0x61,
	0x72, 0x10, 0x01, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x15, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x34, 0x0a, 0x0a,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52, 0x0a, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x3e, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45,
	0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x25, 0x0a, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x53, 0x54, 0x41, 0x44, 0x4f, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x22, 0x5a, 0x0a, 0x19, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12,
	0x3d, 0x0a, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0e,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x4d,
	0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x6e,
	0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49,
	0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x4c, 0x0a,
	0x18, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52,
	0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x18, 0x52,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x1d, 0x0a, 0x09, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x1b, 0x0a, 0x07, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x1a, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0xbe,
	0x01, 0x0a, 0x0d, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x55, 0x45,
	0x47, 0x4f, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x12, 0x2a, 0x0a, 0x08,
	0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x49, 0x64, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x25, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22,
	0x63, 0x0a, 0x0c, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12,
	0x2a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x49,
	0x64, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x6a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x52, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x73, 0x22, 0x7b, 0x0a, 0x0e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x0a, 0x6e, 0x75,
	0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x0c, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f,
	0x6e, 0x64, 0x61, 0x52, 0x0c, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64,
	0x61, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e,
	0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x6e, 0x75, 0x6d,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x52,
	0x0a, 0x6e, 0x75, 0x6d, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x0c, 0x6a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x52, 0x0c, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52,
	0x6f, 0x6e, 0x64, 0x61, 0x22, 0x4c, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12,
	0x41, 0x0a, 0x10, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x52, 0x10, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x65, 0x73, 0x2a, 0x3b, 0x0a, 0x05, 0x4a, 0x55, 0x45, 0x47, 0x4f, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x75, 0x63, 0x65, 0x73, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x69, 0x72, 0x61, 0x72, 0x43, 0x75, 0x65, 0x72, 0x64, 0x61, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x4e, 0x61, 0x64, 0x61, 0x10, 0x03, 0x2a,
	0x2b, 0x0a, 0x06, 0x45, 0x53, 0x54, 0x41, 0x44, 0x4f, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x75, 0x65,
	0x72, 0x74, 0x6f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x69, 0x76, 0x6f, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x47, 0x61, 0x6e, 0x61, 0x64, 0x6f, 0x72, 0x10, 0x02, 0x32, 0xcf, 0x01, 0x0a,
	0x05, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65,
	0x12, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x75, 0x64, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x1a, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65,
	0x30, 0x01, 0x12, 0x3e, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x18,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x74, 0x6f, 0x12, 0x4a, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x12, 0x1c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x75, 0x64, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x1a, 0x1c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x32, 0x46,
	0x0a, 0x04, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x3e, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x74, 0x6f, 0x12, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x75, 0x64, 0x56, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x56, 0x65,
	0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x32, 0xb7, 0x01, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x56, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x53, 0x0a, 0x0f, 0x44,
	0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x1f,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x1a,
	0x1f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73,
	0x32, 0xb7, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x56, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x73, 0x12, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x53, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x1f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x65, 0x76, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x1a, 0x1f, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x65, 0x76, 0x6f, 0x6c,
	0x76, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x72, 0x6f, 0x6a, 0x61, 0x73, 0x31,
	0x34, 0x2f, 0x4c, 0x61, 0x62, 0x32, 0x49, 0x4e, 0x46, 0x33, 0x34, 0x33, 0x2f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_SquidGame_proto_rawDescOnce sync.Once
	file_Proto_SquidGame_proto_rawDescData = file_Proto_SquidGame_proto_rawDesc
)

func file_Proto_SquidGame_proto_rawDescGZIP() []byte {
	file_Proto_SquidGame_proto_rawDescOnce.Do(func() {
		file_Proto_SquidGame_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_SquidGame_proto_rawDescData)
	})
	return file_Proto_SquidGame_proto_rawDescData
}

var file_Proto_SquidGame_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Proto_SquidGame_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_Proto_SquidGame_proto_goTypes = []interface{}{
	(JUEGO)(0),                        // 0: Proto.JUEGO
	(ESTADO)(0),                       // 1: Proto.ESTADO
	(RespuestaUnirse_TIPO)(0),         // 2: Proto.RespuestaUnirse.TIPO
	(*SolicitudUnirse)(nil),           // 3: Proto.SolicitudUnirse
	(*RespuestaUnirse)(nil),           // 4: Proto.RespuestaUnirse
	(*SolicitudVerMonto)(nil),         // 5: Proto.SolicitudVerMonto
	(*RespuestaVerMonto)(nil),         // 6: Proto.RespuestaVerMonto
	(*SolicitudEnviarJugada)(nil),     // 7: Proto.SolicitudEnviarJugada
	(*RespuestaEnviarJugada)(nil),     // 8: Proto.RespuestaEnviarJugada
	(*SolicitudRegistrarJugadas)(nil), // 9: Proto.SolicitudRegistrarJugadas
	(*RespuestaRegistrarJugadas)(nil), // 10: Proto.RespuestaRegistrarJugadas
	(*SolicitudDevolverJugadas)(nil),  // 11: Proto.SolicitudDevolverJugadas
	(*RespuestaDevolverJugadas)(nil),  // 12: Proto.RespuestaDevolverJugadas
	(*JugadorId)(nil),                 // 13: Proto.JugadorId
	(*RondaId)(nil),                   // 14: Proto.RondaId
	(*Jugada)(nil),                    // 15: Proto.Jugada
	(*PaqueteJugada)(nil),             // 16: Proto.PaqueteJugada
	(*JugadasRonda)(nil),              // 17: Proto.JugadasRonda
	(*JugadasJugador)(nil),            // 18: Proto.JugadasJugador
	(*JugadasRondaJugador)(nil),       // 19: Proto.JugadasRondaJugador
	(*Jugadas)(nil),                   // 20: Proto.Jugadas
}
var file_Proto_SquidGame_proto_depIdxs = []int32{
	2,  // 0: Proto.RespuestaUnirse.msgTipo:type_name -> Proto.RespuestaUnirse.TIPO
	13, // 1: Proto.RespuestaUnirse.numJugador:type_name -> Proto.JugadorId
	0,  // 2: Proto.RespuestaUnirse.numJuego:type_name -> Proto.JUEGO
	14, // 3: Proto.RespuestaUnirse.numRonda:type_name -> Proto.RondaId
	16, // 4: Proto.SolicitudEnviarJugada.jugadaInfo:type_name -> Proto.PaqueteJugada
	1,  // 5: Proto.RespuestaEnviarJugada.estado:type_name -> Proto.ESTADO
	18, // 6: Proto.SolicitudRegistrarJugadas.jugadasJugador:type_name -> Proto.JugadasJugador
	13, // 7: Proto.RespuestaRegistrarJugadas.numJugador:type_name -> Proto.JugadorId
	13, // 8: Proto.SolicitudDevolverJugadas.numJugador:type_name -> Proto.JugadorId
	18, // 9: Proto.RespuestaDevolverJugadas.jugadasJugador:type_name -> Proto.JugadasJugador
	13, // 10: Proto.PaqueteJugada.numJugador:type_name -> Proto.JugadorId
	0,  // 11: Proto.PaqueteJugada.numJuego:type_name -> Proto.JUEGO
	14, // 12: Proto.PaqueteJugada.numRonda:type_name -> Proto.RondaId
	15, // 13: Proto.PaqueteJugada.jugada:type_name -> Proto.Jugada
	14, // 14: Proto.JugadasRonda.numRonda:type_name -> Proto.RondaId
	15, // 15: Proto.JugadasRonda.jugadas:type_name -> Proto.Jugada
	13, // 16: Proto.JugadasJugador.numJugador:type_name -> Proto.JugadorId
	17, // 17: Proto.JugadasJugador.jugadasRonda:type_name -> Proto.JugadasRonda
	13, // 18: Proto.JugadasRondaJugador.numJugador:type_name -> Proto.JugadorId
	17, // 19: Proto.JugadasRondaJugador.jugadasRonda:type_name -> Proto.JugadasRonda
	18, // 20: Proto.Jugadas.jugadasJugadores:type_name -> Proto.JugadasJugador
	3,  // 21: Proto.Lider.Unirse:input_type -> Proto.SolicitudUnirse
	5,  // 22: Proto.Lider.VerMonto:input_type -> Proto.SolicitudVerMonto
	7,  // 23: Proto.Lider.EnviarJugada:input_type -> Proto.SolicitudEnviarJugada
	5,  // 24: Proto.Pozo.VerMonto:input_type -> Proto.SolicitudVerMonto
	9,  // 25: Proto.NameNode.RegistrarJugadas:input_type -> Proto.SolicitudRegistrarJugadas
	11, // 26: Proto.NameNode.DevolverJugadas:input_type -> Proto.SolicitudDevolverJugadas
	9,  // 27: Proto.DataNode.RegistrarJugadas:input_type -> Proto.SolicitudRegistrarJugadas
	11, // 28: Proto.DataNode.DevolverJugadas:input_type -> Proto.SolicitudDevolverJugadas
	4,  // 29: Proto.Lider.Unirse:output_type -> Proto.RespuestaUnirse
	6,  // 30: Proto.Lider.VerMonto:output_type -> Proto.RespuestaVerMonto
	8,  // 31: Proto.Lider.EnviarJugada:output_type -> Proto.RespuestaEnviarJugada
	6,  // 32: Proto.Pozo.VerMonto:output_type -> Proto.RespuestaVerMonto
	10, // 33: Proto.NameNode.RegistrarJugadas:output_type -> Proto.RespuestaRegistrarJugadas
	12, // 34: Proto.NameNode.DevolverJugadas:output_type -> Proto.RespuestaDevolverJugadas
	10, // 35: Proto.DataNode.RegistrarJugadas:output_type -> Proto.RespuestaRegistrarJugadas
	12, // 36: Proto.DataNode.DevolverJugadas:output_type -> Proto.RespuestaDevolverJugadas
	29, // [29:37] is the sub-list for method output_type
	21, // [21:29] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_Proto_SquidGame_proto_init() }
func file_Proto_SquidGame_proto_init() {
	if File_Proto_SquidGame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_SquidGame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudVerMonto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaVerMonto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudEnviarJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaEnviarJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudRegistrarJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaRegistrarJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudDevolverJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaDevolverJugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadorId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RondaId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteJugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasRonda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasRondaJugador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_SquidGame_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugadas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_SquidGame_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_Proto_SquidGame_proto_goTypes,
		DependencyIndexes: file_Proto_SquidGame_proto_depIdxs,
		EnumInfos:         file_Proto_SquidGame_proto_enumTypes,
		MessageInfos:      file_Proto_SquidGame_proto_msgTypes,
	}.Build()
	File_Proto_SquidGame_proto = out.File
	file_Proto_SquidGame_proto_rawDesc = nil
	file_Proto_SquidGame_proto_goTypes = nil
	file_Proto_SquidGame_proto_depIdxs = nil
}
